/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PaystackPaymentService } from "../paystackPayment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PaystackPaymentCreateInput } from "./PaystackPaymentCreateInput";
import { PaystackPayment } from "./PaystackPayment";
import { PaystackPaymentFindManyArgs } from "./PaystackPaymentFindManyArgs";
import { PaystackPaymentWhereUniqueInput } from "./PaystackPaymentWhereUniqueInput";
import { PaystackPaymentUpdateInput } from "./PaystackPaymentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PaystackPaymentControllerBase {
  constructor(
    protected readonly service: PaystackPaymentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PaystackPayment })
  @nestAccessControl.UseRoles({
    resource: "PaystackPayment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPaystackPayment(
    @common.Body() data: PaystackPaymentCreateInput
  ): Promise<PaystackPayment> {
    return await this.service.createPaystackPayment({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        reference: true,
        amount: true,
        paymentDate: true,
        status: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PaystackPayment] })
  @ApiNestedQuery(PaystackPaymentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PaystackPayment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paystackPayments(
    @common.Req() request: Request
  ): Promise<PaystackPayment[]> {
    const args = plainToClass(PaystackPaymentFindManyArgs, request.query);
    return this.service.paystackPayments({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        reference: true,
        amount: true,
        paymentDate: true,
        status: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PaystackPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaystackPayment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async paystackPayment(
    @common.Param() params: PaystackPaymentWhereUniqueInput
  ): Promise<PaystackPayment | null> {
    const result = await this.service.paystackPayment({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        reference: true,
        amount: true,
        paymentDate: true,
        status: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PaystackPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaystackPayment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePaystackPayment(
    @common.Param() params: PaystackPaymentWhereUniqueInput,
    @common.Body() data: PaystackPaymentUpdateInput
  ): Promise<PaystackPayment | null> {
    try {
      return await this.service.updatePaystackPayment({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          reference: true,
          amount: true,
          paymentDate: true,
          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PaystackPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PaystackPayment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePaystackPayment(
    @common.Param() params: PaystackPaymentWhereUniqueInput
  ): Promise<PaystackPayment | null> {
    try {
      return await this.service.deletePaystackPayment({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          reference: true,
          amount: true,
          paymentDate: true,
          status: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
