/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CryptoPaymentService } from "../cryptoPayment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CryptoPaymentCreateInput } from "./CryptoPaymentCreateInput";
import { CryptoPayment } from "./CryptoPayment";
import { CryptoPaymentFindManyArgs } from "./CryptoPaymentFindManyArgs";
import { CryptoPaymentWhereUniqueInput } from "./CryptoPaymentWhereUniqueInput";
import { CryptoPaymentUpdateInput } from "./CryptoPaymentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CryptoPaymentControllerBase {
  constructor(
    protected readonly service: CryptoPaymentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CryptoPayment })
  @nestAccessControl.UseRoles({
    resource: "CryptoPayment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCryptoPayment(
    @common.Body() data: CryptoPaymentCreateInput
  ): Promise<CryptoPayment> {
    return await this.service.createCryptoPayment({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        walletAddress: true,
        transactionId: true,
        amount: true,
        paymentDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CryptoPayment] })
  @ApiNestedQuery(CryptoPaymentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CryptoPayment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cryptoPayments(
    @common.Req() request: Request
  ): Promise<CryptoPayment[]> {
    const args = plainToClass(CryptoPaymentFindManyArgs, request.query);
    return this.service.cryptoPayments({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        walletAddress: true,
        transactionId: true,
        amount: true,
        paymentDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CryptoPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CryptoPayment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async cryptoPayment(
    @common.Param() params: CryptoPaymentWhereUniqueInput
  ): Promise<CryptoPayment | null> {
    const result = await this.service.cryptoPayment({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        walletAddress: true,
        transactionId: true,
        amount: true,
        paymentDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CryptoPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CryptoPayment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCryptoPayment(
    @common.Param() params: CryptoPaymentWhereUniqueInput,
    @common.Body() data: CryptoPaymentUpdateInput
  ): Promise<CryptoPayment | null> {
    try {
      return await this.service.updateCryptoPayment({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          walletAddress: true,
          transactionId: true,
          amount: true,
          paymentDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CryptoPayment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CryptoPayment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCryptoPayment(
    @common.Param() params: CryptoPaymentWhereUniqueInput
  ): Promise<CryptoPayment | null> {
    try {
      return await this.service.deleteCryptoPayment({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          walletAddress: true,
          transactionId: true,
          amount: true,
          paymentDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
